[Metadata]
Name=Matugen
Version=0.1
ScaleWithDPI=True

[InputPanel]
NormalColor=#f1dfd9
HighlightColor=#393005
HighlightBackgroundColor=#d5c68e
HighlightCandidateColor=#393005
EnableBlur=False
FullWidthHighlight=True

[InputPanel/Background]
Color=#271d1a
BorderColor=#a08d86
BorderWidth=1

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color=#d5c68e

[InputPanel/TextMargin]
Left=5
Right=5
Top=5
Bottom=5

[Menu]
NormalColor=#f1dfd9
HighlightCandidateColor=#393005

[Menu/Background]
Color=#271d1a
BorderColor=#a08d86
BorderWidth=1

[Menu/Highlight]
Color=#d5c68e

[Menu/CheckBox]
Image=radio.svg

[Menu/SubMenu]
Image=arrow.svg
